/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeriadechela;

import javax.swing.JOptionPane;
import pizzeriadechela.database.MysqlAction;
import pizzeriadechela.database.data.*;
import pizzeriadechela.componentes.Utilidad;

/**
 *
 * @author Anaiza
 */
public class PizzeriaJFrame extends javax.swing.JFrame {

    private MysqlAction _mysqlAction;
    
    /**
     * Creates new form PizzeriaJFrame
     */
    public PizzeriaJFrame( ) {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public PizzeriaJFrame initializate(MysqlAction mysqlAction){
        _mysqlAction = mysqlAction;
        return this;
    }
    
    void enableInicioSesion(Boolean valor){
        _ingresarButton.setEnabled(valor);
        _dniTextField.setEnabled(valor);
        _contraTextField.setEnabled(valor);
    }
    
    void ocultarVentana(){
        _contraTextField.setText("");
        enableInicioSesion(true);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _dniTextField = new javax.swing.JTextField();
        _contraTextField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        _ingresarButton = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _dniTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        _dniTextField.setMaximumSize(new java.awt.Dimension(8, 8));
        getContentPane().add(_dniTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 190, 30));
        _dniTextField.getAccessibleContext().setAccessibleName("_dbiTextField");

        _contraTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        _contraTextField.setMaximumSize(new java.awt.Dimension(4, 20));
        getContentPane().add(_contraTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 190, 30));
        _contraTextField.getAccessibleContext().setAccessibleName("_contrasenniaField");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, 30));

        _ingresarButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        _ingresarButton.setActionCommand("Ingresar");
        _ingresarButton.setLabel("Ingresar");
        _ingresarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _ingresarButtonMouseClicked(evt);
            }
        });
        getContentPane().add(_ingresarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 108, -1));
        _ingresarButton.getAccessibleContext().setAccessibleName("_ingresarBotton");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/0.1.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _ingresarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__ingresarButtonMouseClicked
        // TODO add your handling code here:
        enableInicioSesion(false);
        if (!Utilidad.validarDNI(_dniTextField.getText())){
            JOptionPane.showMessageDialog(null, "El DNI ingresado no es válido.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            enableInicioSesion(true);
            return;
        }
        
        String contrasenia = Utilidad.getCadena(_contraTextField.getPassword());
        
        if (!Utilidad.validarContrasenia(contrasenia)){
            JOptionPane.showMessageDialog(null, "La contraseña ingresada no es valida.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            enableInicioSesion(true);
            return;
        }
        
        CuentaDto cuenta = _mysqlAction.getCuenta(_dniTextField.getText());
        if (cuenta == null){
            JOptionPane.showMessageDialog(null, "La cuenta con el dni ingresado no existe.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            enableInicioSesion(true);
            return;
        }
        
        if (!Utilidad.validarContrasenias(cuenta.getContrasenia(), contrasenia)){
            JOptionPane.showMessageDialog(null, "La contraseña es incorrecta.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            enableInicioSesion(true);
            return;
        }
        
        if (cuenta.getCargo() < 1 || cuenta.getCargo() == 2){
            JOptionPane.showMessageDialog(null, "La cuenta no tiene acceso autorizado.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            enableInicioSesion(true);
            return;
        }
        
        PizzeriaDChelaFrame frame = new PizzeriaDChelaFrame();
                frame.initializate(this, cuenta, _mysqlAction)
                     .setVisible(true);
                ocultarVentana();
    }//GEN-LAST:event__ingresarButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzeriaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzeriaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzeriaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzeriaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzeriaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField _contraTextField;
    private javax.swing.JTextField _dniTextField;
    private javax.swing.JToggleButton _ingresarButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
